### ISSUE TITLE
Epic: Add MEDUSA 2.0 pollutant model

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#146]
The model must be fully controllable by the digital twin.

- [ ] As a water scientist, I want to be able to model a rainfall event based on configurable parameters and identify sources and quantities of pollutants associated with the event. This will be a separate modelling mode than flood modelling.
- [ ] This model should be based on MEDUSA2.0, and could potentially be reimplemented, or be built using DHI’s existing software, pending investigation.
- [ ] Data should be outputted as spatial vector layers detailing sources of pollutants and their contributing pollutant loads.
- [ ] As a water scientist, I want to be able to adjust inputs to pollutant modelling, such that I can use the tool to model bounds for uncertainties in my modelling.

**Comment by LukeParky** [comment]
Added sub-issue for working on the core backend processing task: #158

**Comment by LukeParky** [comment]
This issue has been split up into multiple smaller issues so they can be tackled separately
Core - #158 
API definition - #161
Backend controls - #163
Geoserver for medusa outputs - #160
Front-end controls and visualisation - #162
